# Generated by Django 5.2.9 on 2026-02-24 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_denguecase'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositiveDengueCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150)),
                ('cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('test_location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dengue_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='positive_details', to='api.denguecase')),
            ],
        ),
    ]
