name: Build Android APK (Kivy)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Baixando o Código do Repositório
        uses: actions/checkout@v4

      - name: Preparar Receita do VigiAA (buildozer.spec)
        run: |
          # 1. Instalamos o buildozer rapidinho só para criar a receita
          pip install buildozer
          
          echo "📂 Entrando na pasta frontend..."
          cd frontend
          
          # 2. Criamos a receita padrão
          buildozer init
          
          # 3. Modificamos a receita com o Python
          python3 -c "
          with open('buildozer.spec', 'r') as f: text = f.read()
          
          text = text.replace('title = My Application', 'title = VigiAA')
          text = text.replace('package.name = myapp', 'package.name = vigiaa')
          text = text.replace('source.include_exts = py,png,jpg,kv,atlas', 'source.include_exts = py,png,jpg,jpeg,kv,atlas,json,ttf')
          text = text.replace('requirements = python3, kivy==2.0.0', 'requirements = python3, kivy==2.3.1, kivymd, requests, plyer, cython')
          text = text.replace('# android.permissions = INTERNET', 'android.permissions = INTERNET, ACCESS_FINE_LOCATION, ACCESS_COARSE_LOCATION')
          text = text.replace('# android.api = 27', 'android.api = 33')
          text = text.replace('# android.minapi = 21', 'android.minapi = 24')
          
          with open('buildozer.spec', 'w') as f: f.write(text)
          "

      - name: Fabricar o APK com Action Oficial
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: frontend
          buildozer_args: android debug

      - name: Disponibilizar APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: vigiaa-apk-release-${{ github.run_number }}
          path: ${{ steps.buildozer.outputs.filename }}